import json
import subprocess
import sys
import os
from pathlib import Path
from langchain.tools import tool

USER_CONTEXT_FILE = "user_context.json"
SUGGESTED_PLAN_FILE = "suggested_plan.json"
PROJECT_DIR = Path(__file__).parent

@tool
def fetch_user_context(goal: str = None, notes: str = None) -> str:
    """
    Fetches the user's Garmin profile, stats, recent activities, and calendar goals.
    Use this tool when the user asks to check their status, update data, or start planning.
    
    Args:
        goal: (Optional) A specific training goal to set (e.g. "Sub 3:14 Marathon"). 
              If not provided, the tool will try to detect from Garmin calendar.
        notes: (Optional) User specific notes for the upcoming period.
    
    Returns:
        A JSON string containing the user's context (profile, activities, stats, goals).
    """
    cmd = [sys.executable, str(PROJECT_DIR / "agent_tool.py"), "context", "--days", "14"]
    
    if goal:
        cmd.extend(["--goal", goal])
    if notes:
        cmd.extend(["--notes", notes])
        
    try:
        subprocess.run(cmd, check=True, capture_output=True, text=True, cwd=str(PROJECT_DIR))
        context_file = PROJECT_DIR / USER_CONTEXT_FILE
        if context_file.exists():
            with open(context_file, "r") as f:
                data = json.load(f)
                return json.dumps(data, indent=2)
        else:
            return "Error: Context file was not created."
    except subprocess.CalledProcessError as e:
        return f"Error running fetch command: {e.stderr}"
    except Exception as e:
        return f"Error: {str(e)}"

@tool
def save_generated_plan(plan_json: str) -> str:
    """
    Saves the training plan generated by the AI to the file system.
    ALWAYS call this before executing/uploading a plan.
    
    Args:
        plan_json: A valid JSON string representing the list of workouts.
                   Each workout must have 'workoutName', 'scheduleDate' (YYYY-MM-DD), 'description',
                   and 'steps'.
    
    Returns:
        A success message or error string.
    """
    try:
        plan_data = json.loads(plan_json)
        with open(SUGGESTED_PLAN_FILE, "w") as f:
            json.dump(plan_data, f, indent=2)
        return f"Plan saved successfully to {SUGGESTED_PLAN_FILE}. You can now ask the user for confirmation to execute it."
    except json.JSONDecodeError as e:
        return f"Error: Invalid JSON format provided. {e}"
    except Exception as e:
        return f"Error saving plan: {str(e)}"

@tool
def execute_upload_plan() -> str:
    """
    Uploads and schedules the workouts from the saved plan to Garmin Connect.
    ONLY call this tool after the user has explicitly confirmed they want to upload the plan.
    
    Returns:
        The output log of the upload process.
    """
    cmd = [sys.executable, str(PROJECT_DIR / "agent_tool.py"), "execute", "--yes"]
    try:
        result = subprocess.run(cmd, check=True, capture_output=True, text=True, cwd=str(PROJECT_DIR))
        return result.stdout
    except subprocess.CalledProcessError as e:
        return f"Error executing plan: {e.stdout}\n{e.stderr}"
    except Exception as e:
        return f"Error: {str(e)}"
